### ISSUE TITLE
No 'ping' endpoint

### ISSUE THREAD

**Issue by davidlukerice** [Woopra/node-woopra#11]
We're using `node-woopra` to communicate all analytics data to Woopra from our client. So instead of sending event/client/ping data from the browser to Woopra through the Woopra `js-client-tracker`, it's sending it to our server, which then relays the data to Woopra through `node-woopra`.

Currently, node-woopra doesn't provide a ping interface and adding something like the following doesn't seem to work:
```
ping: function(cb) {
  return this.request('ping', {}, cb);
},
```

the issue we're having is that even if we hit the ping interface every 12s or so, the `Visit Duration` report on the Woopra dashboard doesn't seem to be updated. Is there any particular piece of information that needs to be sent during a ping to get it to work?

**Comment by philosoralphter** [comment]
Hey @davidlukerice,  I believe that should work...The tricky part is, that you need to make sure you have the correct instance of the tracker for each client session.  The ping won't do anything if there isn't some identifier for the user and thus the session that you want to keep online.  Generally you call `reset()` or `initialize()` a new tracker instance for each client session.  If the pings are running on the wrong instance, or after the reset, It wont work.

I did some brief tests and I believe it should work.  Perhaps you can throw a log message into your `request()` method to inspect requests going out to `/track/ping`.  If you could share that here, I may be able to help more.

Also, if you email support@woopra.com and ask to talk to Ralph about the node sdk, we can discuss in more detail and I can take a look at your project and see what data is making it and if there are any errors, etc.

I like this idea, so once we get it working, I'd love to merge a PR.

Thanks!

**Comment by davidlukerice** [comment]
The sails controller on my server runs what amounts to the following when it gets pinged
```
woopra.client({
	ip: req.ip,
	screen: req.body.screen,
	referrer: req.body.referrer,
	language: req.body.language,
	'user-agent': req.headers['user-agent']
});
woopra.identify(req.user.email);
woopra.ping({}, (e, res) => console.log(e));
```

where `woopra` is
```
const woopra = new Woopra('[redactedDomain]');
```

The ping then generates the following request out
```
/track/ping?
  user-agent=Mozilla%2F5.0%20(Macintosh%3B%20Intel%20Mac%20OS%20X%2010_12_6)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F61.0.3163.79%20Safari%2F537.36
  &ip=%3A%3A1
  &language=en-US
  &referrer=https%3A%2F%2F[redactedDomain]%2F
  &screen=2560x1440
  &app=node
  &website=[redactedDomain]
  &cv_email=david.rice%2B71%40[redactedDomain]
  &
```
and I don't receive any errors in the callback.

Looking at the [http-tracking-api](https://www.woopra.com/docs/developer/http-tracking-api/#Ping_requests), it uses the `host`, `response`, `cookie`, & `timeout` query parameters. Do I need any of these? or should the above request be sufficient?

**Comment by philosoralphter** [comment]
OK I think I figured it out.  Two things: your signature for `ping` is `(optionsObj, cb), but you are calling with just the callback, and there is no logic to handle that as there is in the built-in `track()` method.

Secondly, the ping does need the cookie.  So call `woopra.client({cookie: <BROWSER COOKIE OR DEVICE ID>})`  You can handle your own cookies or use window.woopra.cookie on the client side to get our cookie.

so here is some test code that I used to get this working:
```
let woopra = new Woopra('redacted.com');
woopra.initialize();
woopra.client({cookie:'1234asdf'});
woopra.identify('ralph-ping-test@woopra.com');
woopra.track('pv');

setInterval(() => {
woopra.ping({}, (e, res) => console.log(e, res.statusCode));

}, 2000);
```

I will add this ping functionality to the roadmap for this sdk, and will consider the requirement that there be a cookie at all as well.  Until then, I think your patched code will work fine, just send a cookie, and use `ping` as you write it.  I will try and remember to let you know when that functionality is added, and if anything changes about pings and cookies.

**Comment by davidlukerice** [comment]
ok cool! Yah, my ping signature/calling method has been changing during the course of testing out what works or not.

I'll definitely give adding the cookie ago. We no longer include the Woopra `js-client-tracker` at all in the page, so I'll look into generating our own cookies.

Thanks for all the quick responses.

**Comment by philosoralphter** [comment]
No problem!

I'd recommend using cookies so you can tie pre-logged-in behavior, and marketing website behavior to logged-in, in-web-app behavior anyway.

**Comment by davidlukerice** [comment]
Yup, everything seems to be working correctly with adding a cookie. Any eta on a merge for that branch? Or anything I can help with? Would prefer to not have to `npm install` from a non official source.
