### ISSUE TITLE
Publish 1.0.2

### ISSUE THREAD

**Issue by garrettjoecox** [Woopra/node-woopra#13]
Hey there, 

Our platform is relying on the functionality added in the version 1.0.2. Since it is not published we have taken advantage of NPM's ability to install from github, listing`"woopra": "github:woopra/node-woopra"` in the package.json.

Sadly this functionality seems to have broken in a newer version of NPM (issue listed here: https://github.com/npm/npm/issues/17379)

Is there anything holding back from publishing 1.0.2 to npm? Otherwise we'll have to use one of the odd workarounds.

**Comment by philosoralphter** [comment]
Hi, 
Sorry about that, it is now published.
--Ralph
