### ISSUE TITLE
Client push not responding

### ISSUE THREAD

**Issue by jamesjjk** [Woopra/node-woopra#4]
When setting client data only (with a cookie) and pushing it Woopra doesn't seem to respond. This may be because the push function uses the identify route.. Also can't add push method in chain on client as client method does not return woopra object (this).

```
woopra.client({'cookie': XXX, 'screen': XXX});
woopra.push();
```

**Comment by philosoralphter** [comment]
Hi James.  The data set on the client object is not conceptually enough to send an event or an identify call to Woopra.  The client() method essentially sets metadata for the next request that goes out.  It does not return the whole object--we can consider changing this but it is a little messy and may require a new API for code cleanliness. (the client() method is also used as a getter when passed no arguments)

If you are trying to run an identify(), then you need at least a higher-order id for the visitor to tie to that cookie.  For instance an email, or a database id.  Then you can call .push() (and you can chain that off of the identify call).

On the other hand, if you are tracking an anonymous visitor, you will need to call .track() and at least put in an event name (first argument).

So to send data to woopra, you want to set the client data first, then either call `.track(EVENT_NAME, {...OTHER ACTION PROPERTIES...}, CALLBACK)`

or `.identify(EMAIL, {...OTHER VISITOR PROPERTIES...}).push(CALLBACK)`

or both: `.identify(email, {id: 123}).track('form_submit', (done) => {return true;})`

Let me know what you think
